# Simple go lint and test.
os: linux
dist: bionic
language: go
go:
  - 1.15.x
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
script:
  - GOOS=linux golangci-lint run --enable-all
  - GOOS=darwin golangci-lint run --enable-all
  - GOOS=windows golangci-lint run --enable-all
  - GOOS=freebsd golangci-lint run --enable-all
  - go test -race -covermode=atomic ./...
  # Test 32 bit OSes.
  - GOOS=linux GOARCH=386 go build .
  - GOOS=freebsd GOARCH=386 go build .
  # Avoid cross pollution.
  - grep -riE 'readar|sonar|lidar' radarr  && exit 1
  - grep -riE 'radar|sonar|lidar'  readarr && exit 1
  - grep -riE 'readar|radar|lidar' sonarr  && exit 1
  - grep -riE 'readar|radar|sonar' lidarr  && exit 1
